src/Features.hpp, src/Features/PlayerTrace.cpp, src/Features/PlayerTrace.hpp, src/SAR.cpp, src/SourceAutoRecord.vcxproj, src/SourceAutoRecord.vcxproj.filters
Adds functionality do record the player path and groundframes, as well as display it back for analysis.
=> feat: add sar_player_trace

src/Features/Tas/TasPlayer.cpp
Change tas help strings to match the format of all others
=> fix: format tas help strings

src/Features/Tas/TasTools/StrafeTool.cpp, src/SourceAutoRecord.vcxproj, src/SourceAutoRecord.vcxproj.filters
Fixed the issue where line following algorithm would try its hardest to follow already defined line, even if deviated from it. I taught it that it's okay to fail and it shouldn't push itself that hard. Now it follows the new line if deviated from the old one more than it should.
Additionally, added some comments to increase the group of people who can understand this code from no one to me.
Also, since mlugg hates Windows users, included his TAS tools files into VS project.
=> fix: improve TAS autostrafer

src/Features/Hud/InputHud.cpp, src/Features/Hud/TasControllerHud.cpp, src/Features/Hud/TasControllerHud.hpp, src/Features/Tas/TasPlayer.cpp, src/Modules/Client.cpp, src/Modules/Server.cpp, src/SourceAutoRecord.vcxproj, src/SourceAutoRecord.vcxproj.filters
Special HUD, `sar_tas_controller_hud`, allowing to preview movement and view analog inputs made by the TAS virtual controller.
Along with that, new ihud mode which doesn't include WSAD and have all buttons laid horizontally, so it is possible to align it nicely with the controller HUD in order to create Mega TAS HUD.
=> feat: TAS Controller HUD

src/Cheats.cpp, src/Features.hpp, src/Features/ReloadedFix.cpp, src/Features/ReloadedFix.hpp, src/Features/Tas/TasPlayer.cpp, src/Features/Tas/TasPlayer.hpp, src/Modules/Engine.cpp, src/Modules/Server.cpp, src/SAR.cpp, src/SourceAutoRecord.vcxproj, src/SourceAutoRecord.vcxproj.filters
Portal Reloaded uses `change_portalgun_linkage_id` command in order to handle placing present and future portals, as well as a time portal. This command, however, is cheat protected, so in addition, the game enables and disables `sv_cheats` when attempting to use that command. This is inconvenient for TASers and routers, who prefer to have server cheats constantly enabled. This can be fixed by "aliasing" `sv_cheats` so that it can never be executed again. 
However, that eliminates pretty useful glitch called Portal Time Heist, which abuses the fact that we can cause the game to disable server cheats before changing portal gun linkage ID, basically allowing us to place future portals in present and vice-versa.
This fix attempts to eliminate those issues by separating game's and user's …
=> feat: fix Reloaded time portals invading player's console.

src/Features/PlayerTrace.cpp, src/Features/PlayerTrace.hpp
Adds more colors on the player trace:
- Green when above 300ups
- Brown when speedlocked
- Yellow when the maximum turning is reached
=> feat: improve player trace

src/Features/Tas/TasParser.cpp
Also works with opening and closing the comment in the same line (e.g.: 5>||say test /\*comment\*/|).
I also fixed the bug that if you use start cm, in the raw TAS file would not be the map name (fix: #53)
=> feat: add TAS parser multiline comments with /*, */

src/Features/Hud/InputHud.cpp, src/Features/Hud/InputHud.hpp
This allows you to add any key to ihud, by using the command `sar_ihud_add_key <key>`. This will add a new key element to ihud that you can modify just like any other element by using the key name as the name in `sar_ihud_modify`.
Example: `sar_ihud_add_key p` => `sar_ihud_modify p x=2`
You can also now get the values of the parameters each element has, by using `sar_ihud_modify` but not assigning the values.
Example: `sar_ihud_modify movement enabled` => `movement: enabled=1`
This works with every parameter a key element has, with multiple parameters in the same command and with "all" as the element name.
=> Custom keys for iHud

src/Features/Tas/TasPlayer.cpp
Due to the implementation of `nopitchlock`, the move analog y was able to go outside of the normal range of controller inputs, mostly visible on the ihud.
By clamping the move analog, this is prevented.
Thankfully this doesn't break any TASses since the input was clamped server side.
=> Fix analog move going out of the unit circle.

src/Modules/Console.hpp, src/SAR.cpp
The pride feature was not thread safe at all (untested?)
Now it is :)
=> fix: thread-safe pride

.github/workflows/CD.yml, .github/workflows/CI.yml
See commits.
#
* CI and CD can probably be made into one workflow through the clever use of if conditions.
* If Release+Debug or x86+x64 builds are desired, build matrixes should be added.
=> CI+CD: Improvements

src/Features/Speedrun/SpeedrunTimer.cpp, src/Features/Speedrun/SpeedrunTimer.hpp
also unlimit args for `sar_speedrun_recover` so breakset doesn't confuse things
=> feat: allow time for `sar_speedrun_offset`

src/Features/Hud/Hud.cpp
optionally could refactor `SetValue`s to the bottom to avoid half-functionality i.e. `ss_pip_align top foo`
=> feat: `sar_pip_align`

src/Cheats.cpp, src/Cheats.hpp, src/Features/Cvars.cpp
unprotecting a command (r_flashlightbrightness) that should not be protected anyways
i think it gets changed by the map normally (?) but its cheat protected in cm
feat: makes game look better (and how it should be)
default look (non cm) (fixed cm look)
default cm look
=> env_projectedtexture fix

src/Features/ConfigPlus.cpp
- Primitive svar completion for `svar_get`, `svar_substr`, `svar_[no_]persist`, `svar_capture`, `svar_from_cvar`, and operations
- Remove the single-argument limit on `svar_set` (e.g. `svar_set a b c` => `a = b c`)
- `sar_on_{x}_list` for debugging / curiosity. arguably could add a index to the list and `sar_on_{x}_remove <i>` but that's too fancy
- `$0`/`$+0` in expansion -- quite dubious, feel free to drop but I don't see the harm
- Re-order the code to be feature-contiguous
- Floating point svar math!! Adds `svar_round`, `svar_floor`, `svar_ceil`, and `svar_abs` (the last of which is pretty superfluous)
=> feat: Config plus improvements (again...)

src/Features/Speedrun/Categories.cpp, src/Features/Speedrun/Categories.hpp, src/Features/Speedrun/SpeedrunTimer.cpp, src/Features/Speedrun/SpeedrunTimer.hpp, src/Modules/Client.cpp
optional legacy (chat) mtriggers
advantage: being able to just open chat and see previous run's mtriggers
some pros asked for this
spice:
-changable formatting using keywords (!map, !seg, !tt, !st)*
eg sar_mtrigger_legacy_format "!seg -> !tt (!st)" will result in something like "Portal Trigger -> 6.567 (1.333)"
*tt being total time
*st being split time
-changable text color
=> feat: legacy mtriggers + some spice

src/Features/EntityList.cpp, src/Features/EntityList.hpp, src/Modules/EngineDemoPlayer.cpp, src/Modules/EngineDemoRecorder.cpp, src/Modules/Server.cpp
This PR patches `sar_ent_slot_serial` to change the slot's serial number **the next time the slot is removed** if it can't do it immediately.
Possible problems:
- The slot is removed more than once, hence making the serial number too high
- The slot isn't removed on every load, making the behavior unpredictable
=> fix: allow `sar_ent_slot_serial` ingame

src/Cheats.cpp, src/Features/Cvars.cpp, src/Features/Hud/Hud.cpp, src/Features/Hud/Hud.hpp, src/Features/Hud/InputHud.cpp, src/Features/Hud/SpeedrunHud.cpp, src/Features/Hud/Toasts.cpp, src/Modules/Console.cpp, src/Modules/VGui.cpp, src/Variable.cpp
When was the last time someone used `sar_hud_inspection`? Is it worth cheat-protecting? Certainly looks quite cheaty
Newly unrecorded commands:
- `sar_fast_load_preset`
- `sar_hud_*`
- `sar_ihud_*`
- `sar_toast_*`
- `sar_sr_hud_*`
- `sar_echo[_nolf]`
Modified help strings for:
- `help`
- `sar_<x>_setpos`
- `sar_hud_order_reset`
LMK if there's anything else that deserves not recording :)
=> fix: dont record various commands

docs/contributing.md, src/Cheats.cpp, src/Command.hpp, src/Features/ConfigPlus.cpp, src/Features/Demo/GhostEntity.cpp, src/Features/Hud/Crosshair.cpp, src/Features/Hud/Hud.cpp, src/Features/Hud/InputHud.cpp, src/Features/Speedrun/SpeedrunTimer.cpp, src/Features/WorkshopList.cpp, src/Game.cpp, src/Game.hpp
- `cvar:<cvar>` and `#<cvar>` parsing for `cond` (LHS and RHS of `a=b`). If a command or unknown variable is used, it is assumed to be empty.
- `%<string>` parsing for `cond` (LHS of `a=b`)
- `sar_hud_{show,hide}_text all` at the behest of RealCreative
- refactored references of `xxx_CompletionFunc` to the helpful macro `AUTOCOMPLETION_FUNCTION(xxx)`
The symbols `#` and `%` are negotiable.
=> feat: yet more config+ improvements

src/Features/ConfigPlus.cpp
I'm working on making the most helpful and 'readable' (:skull:) viewsnap configs of all time, but some calculated snaps just don't work because you either get a short decimal number or a short scientific notation, with 6 significant digits, which isn't precise enough to calculate accurate sensitivities/m_yaw.
I chose 17 because that's what stackoverflow said was lossless
=> fix: improve precision of floating svar things

src/Features/EntityList.cpp
Resolves: `sar_ent_slot_serial` isn't cheat protected #147
=> fix: cheats for `sar_ent_slot_serial`

src/Features/Hud/Hud.cpp
When an invalid text index is passed to `sar_hud_show_text`, the help string for `sar_hud_hide_text` is printed.
```
sar_hud_show_text a
```
=> fix: `sar_hud_show_text` error message

src/Features/Tas/TasTools/AngleToolsUtils.cpp, src/Features/Tas/TasTools/AngleToolsUtils.hpp, src/Features/Tas/TasTools/AutoAimTool.cpp, src/Features/Tas/TasTools/SetAngleTool.cpp, src/Features/Tas/TasTools/SetAngleTool.hpp, src/SourceAutoRecord.vcxproj, src/SourceAutoRecord.vcxproj.filters
Adds three additional easing types when interpolating to the desired angle using `setang` TAS automation tool: `sine`/`sin`, `cubic` and `exponential`/`exp`. A type should be given as a fourth parameter to setang. By default, it's still using linear interpolation, meaning this change should be backwards-compatible and doesn't require new script version.
All interpolation type went through very basic tests (me running a single setang for each type), but it would be nice for someone to make some further testing:
- verify if previously made TAS scripts still function properly
- attempt to interrupt `setang` with another `setang`
- check what happens if you pass through the portal while `setang` is in use and if the behaviour is consistent with previous version
=> feat: add easing types for setang tas tool

src/Modules/Engine.cpp
because a. `engine->IsOrange()` is apparently false in orange demos, and
b. angles are apparently always stored in slot 0 in demos
Resolves: #169
=> fix: orange demo angles

src/Features/Hud/Watermark.cpp
Improves development build watermark. It's now less invasive while still informative.
|Before|After| 
|---|---|
|![20230511223536_1](https://github.com/p2sr/SourceAutoRecord/assets/16310330/64ddc0f8-f23d-49f7-8b68-b04a68cecac3)|![20230511223352_1](https://github.com/p2sr/SourceAutoRecord/assets/16310330/0632c502-eaa1-42e9-b1ee-4a57de7d9b6c)|
=> feat: improve dev watermark ux

src/Features/Camera.cpp, src/Features/Camera.hpp
- Draws camera path
- Shows keyframe points in red, and current cinematic position in yellow, as lil' camera boxes
- Of course, FOV, roll, and aspect ratio etc is taken into account when drawing them
- Controlled by `sar_cam_path_draw`, disabled by `sar_cam_control 2`
- Added `sar_cam_path_goto` to tp to a certain frame in drive mode
- **Removed `sar_cam_path_showkfs` in favor of `sar_cam_path_getkfs`**
See [P2SR Discord](https://discord.com/channels/146404426746167296/811780246608281650/1114185964995219527) for discussion, I settled on this shape for the lil' camera boxes
=> feat: draw cinematic camera path

src/CrashHandler.cpp
The `RemoveVectoredExceptionHandler` API takes a handle created by `AddVectoredExceptionHandler` as an argument and not a pointer to the handler function. This fixes a crash when the process tries to call the handler function even when the module is unloaded.
=> fix: clean up of VEH

cvars.js, docs/contributing.md, docs/cvars.md, src/Features/Hud/Hud.cpp
Changes:
- `cvars.js` - cvar description pipe escape, path fallback to cwd, filter out custom (`sar_alias`/`sar_function`) and internal (`_sar_svar_capture_stop`) cvars, and add EOF LF in generated file
- `docs/cvars.md` - regen
- `docs/contributing.md` - add contrib tutorial for cvars.js
- `src/Features/Hud/Hud.cpp` - fix `sar_hud_fps` helpstr to match docs (I still don't see why this HUD exists though)
Should `cvars.js` be in `docs`? To make it more obvious what it's for
=> docs: update cvars list and generator

src/Features/ConfigPlus.cpp, src/Features/Demo/GhostRenderer.cpp
Added a print upon succeeding if check, and added extra condition to if check. This condition was needed in the case where you are in a co-op game, then leave, and try to the run to command. Before it would just print "0" in console after doing so.
=> fix: sar_get_partner_id

src/Modules/Client.cpp
Skips to the next level in workshop (MRCC / casual QoL), subject to squash. Linux works, I've tested it
Fixes #138
=> feat: `sar_workshop_skip`

src/Features/AutoSubmit.cpp
Added commands:
- `sar_get_mtriggers <rank=wr>` - Allows the retrieval of mtriggers on the current map, with a variable to change which rank's mtriggers you receive. If no rank is given, it is assumed you want to retrieve WR.
- `sar_get_mtriggers_map <map=current> <rank=wr>` - Allows the retrieval of mtriggers on any map, with variable to change map and which rank's mtriggers you receive. If no rank is given, it is assumed you want to retrieve WR. If no map OR rank is given, it is assumed current map and WR.
=> feat: mtrigger retrieval commands

src/Modules/Server.cpp
Fixes #222
Needs testing on Linux (p2 + reloaded/mel) @NeKzor . Omitted on TWTM/aptag.
Effectively nop'd the `!client->CanHearAndReadChatFrom( pPlayer )` call in `Host_Say`, allowing messages to be sent while dead, and the receiver is alive. Unfortunately this also kills the behaviour of the `ignoremsg` clientcommand.
=> fix: NetMessage while dead

src/Features/Tas/TasTools/CheckTool.cpp, src/Features/Tas/TasTools/CheckTool.hpp
Adds an option to the tas check tool to check for velocity on all 3 axis. Syntax is `200>>check vel z > 200`. This would reset if velocity is not over 200. Cant test Linux but I would assume that it works.
=> feat: velocity check tool for tas

src/Modules/Server.cpp
Fixing `InitCMFlagHook` that happens every game tick outside of CM, significant improvement for cpu low1% fps.
=> fix: InitCMFlagHook

src/Features/Hud/StrafeQuality.cpp
Stopping strafe quality hud from allocating dynamic memory and computing when disabled.
=> fix: optimization of strafe quality hud

docs/cvars.md, src/Features/Hud/ScrollSpeed.cpp, src/Features/Hud/ScrollSpeed.hpp, src/Modules/Client.cpp, src/Modules/Server.cpp
Rework of sar_scrollspeed to make it nicer and more informative
- Refreshes if re-enabled
- Properly hides outside game session
- Has information about individual scroll intervals (shows amount of groundframes you can get for each scroll)
- Offsets for both tilebox and scroll average bar can be adjusted and disabled separately (sar_scrollspeed 2 and 3)
duplicate of [#265 ](https://github.com/p2sr/SourceAutoRecord/pull/265) to avoid merge commits in the branch
=> Feat: Scrollspeed rework

src/Event.hpp, src/Features/GroundFramesCounter.cpp, src/Features/GroundFramesCounter.hpp, src/Features/Hud/PerformanceHud.cpp, src/Features/Hud/PerformanceHud.hpp, src/Features/Hud/RhythmGame.cpp, src/Features/Hud/RhythmGame.hpp, src/Features/Hud/ScrollSpeed.cpp, src/Features/Hud/ScrollSpeed.hpp, src/Features/Hud/StrafeQuality.cpp, src/Features/Hud/StrafeQuality.hpp, src/Modules/Client.cpp, src/Modules/Engine.cpp, src/Modules/Server.cpp
Moving Server::ProcessMovement function calls to process movement events so features' entry points are always standart.
Fixing Rhythmgame hud doing calculations when disabled
=> Refactor: process movement events

docs/cvars.md, src/Modules/Client.cpp, src/Modules/Client.hpp, src/Offsets/INFRA 6905.hpp, src/Offsets/Portal 2 5723.hpp, src/Offsets/Portal 2 8151.hpp, src/Offsets/Portal 2 8491.hpp, src/Utils/Memory.cpp, src/Utils/Memory.hpp
By patching the branch instruction, force the multiplayer portal/ghostportal material when using sar_portalcolor_enable on SinglePlayer.
Overriding `gamerules->IsMultiplayer` wont work in neither of the functions because that would cause the code to deref `PortalMPGameRules()->IsCoOp()`, which its null on single player.
I'm not familiar with the code base, so if there is something that could improve, i'll appreciate the advice
TODO:
Implement the same for Linux, and if relevant, older builds of portal, should be possible and in fact, i do know where each function is located at `client.so`, but i don't know any good tools like cheat engine for Linux to reverse engineer the game
=> Feat: Improve `sar_portalcolor_*` on SinglePlayer

docs/cvars.md, src/Features/Speedrun/Categories.cpp
This was a feature [requested by Rattlé on Discord](https://discord.com/channels/146404426746167296/811780246608281650/1318579629254246400). This pull request adds the variable `sar_speedrun_triggers_info` which, when set, prints information about the player's position/velocity to the console once they activate a zone trigger speedrun rule.
If set to `1`, prints full rule name, position and velocity coordinates.
If set to `2`, prints just the horizontal velocity on one line.
=> feat: Implement `sar_speedrun_triggers_info`

src/Features/Hud/LPHud.cpp, src/Game.cpp, src/Interface.cpp, src/Interface.hpp, src/Modules/Client.cpp, src/Offsets/Portal 2 4554.hpp, src/Offsets/Portal 2 9568.hpp, src/SAR.cpp
This was meant to be a force push on the previous PR, but then the PR was merged 8 minutes before I went to go message AMJ to tell him not to merge yet (oops lol).
Anyways, made the thing in LPHud early return, demystified some memes with the MsgFunc_SayText(2) hook, and mostly undid/cleaned up the changes to Interface::GetPtr in favor of a simpler solution. (Related to that, the console module is now initialized first before any other modules, so that it is available immediately within the plugin.)
In context to the above, it seems like when the NetMessage stuff for coop was first added, mlugg was originally writing it around SayText2 and then switched to SayText during feature dev without renaming it (or just mistakenly wrote SayText2 because the offset used …
=> Clean up some trolling from the previous PR

src/Features/Speedrun/Rules.cpp
The `SpeedrunTimer::TickRules` function seemingly attempts to track only those portals shot by players, as evidenced by the queries for a player handle, followed by queries for the weapon handle. However, this is not an exhaustive check, and can lead to false positives in some cases.
For example, if the player has a single-portal device, a secondary linked portal opened via map logic will still count as being owned by the player's portal gun. This is likely because the portal gun is still _linked_ to that orange portal, despite not being able to create it. This becomes an issue in cases where SAR's demo data is used to count portal placements in custom maps.
To fix this, I've added a check for the `m_hFiredByPlayer` handle of the portal, which seems to only be valid when the portal has …
=> Check m_hFiredByPlayer when tracking portal rules

docs/cvars.md, src/Cheats.cpp, src/Cheats.hpp, src/Modules/Server.cpp, src/Offsets/Portal 2 9568.hpp
Enables the loading dots during transitions/loads in coop. Linux is not supported currently.
=> feat: loading dots on coop map loads

src/Cheats.cpp, src/Cheats.hpp, src/Modules/Server.cpp, src/Offsets/Portal 2 9568.hpp
Disables the autograb feature in coop. Host dependent patch. Linux is not supported currently.
=> feat: autograb toggle support
