src/Features/PlayerTrace.cpp
src/Features/PlayerTrace.hpp
src/Game.cpp

- greatly reduced ram usage
- support for multiple traces
- more control over drawing of the traces
- more accurate speed deltas

feat: improve player trace

---

src/Features/Hud/VelocityGraph.cpp
src/Features/Hud/VelocityGraph.hpp
src/SourceAutoRecord.vcxproj
src/SourceAutoRecord.vcxproj.filters

Shows velocity and takeoff velocity with a graph.
Colors represent:
Green: gained velocity
Orange: velocity is same as before
Red: lost velocity

Velocity graph hud

---

src/Features/Hud/VelocityGraph.cpp
src/Features/Hud/VelocityGraph.hpp
src/SourceAutoRecord.vcxproj.filters

changed default font index
added toggle for background
added toggle for showing takeoff speed on graph
added a rainbow mode for the velocity text (goes around hue circle using velocity value)

some new velocity graph features, variables, changes

---

src/Features/Hud/Hud.cpp
src/Features/Tas/TasParser.cpp
src/Features/Tas/TasPlayer.cpp
src/Features/Tas/TasPlayer.hpp
src/Features/Tas/TasTools/AbsoluteMoveTool.cpp
src/Features/Tas/TasTools/AutoAimTool.cpp
src/Features/Tas/TasTools/AutoJumpTool.cpp
src/Features/Tas/TasTools/SetAngleTool.cpp
src/Features/Tas/TasTools/StrafeTool.cpp

I also took this opportunity to make more helpful error messages for the tool args
I also took a shot at fixing #54 however the TAS often desyncs which I doubt can be fixed

fix: crashes from wrong tas tool arguments and some minor fixes

---

src/Features/PlayerTrace.cpp
src/Features/PlayerTrace.hpp
src/Features/Tas/TasTools/AbsoluteMoveTool.cpp
src/Features/Tas/TasTools/AbsoluteMoveTool.hpp
src/Modules/Server.cpp
src/Utils/SDK.hpp

Changes:
- Add a strength parameter to the absmov tool
- fix player trace bugs (coop and edge case with multiple traces)
- Add sar_player_trace_teleport_at

A few trace fixes and a tas feature

---

src/Features/Hud/PortalPlacement.cpp
src/Features/Hud/PortalPlacement.hpp
src/Features/Speedrun/SpeedrunTimer.cpp
src/Features/Speedrun/SpeedrunTimer.hpp
src/Features/Tas/TasPlayer.cpp
src/Features/Tas/TasPlayer.hpp
src/Features/Tas/TasTools/StrafeTool.cpp
src/Games/Linux/Portal2.cpp
src/Games/Windows/Portal2.cpp
src/Modules/Server.cpp
src/Modules/Server.hpp
src/SourceAutoRecord.vcxproj
src/SourceAutoRecord.vcxproj.filters
src/Utils/SDK.hpp

Features:
- HUD that indicates if a portal would place where the player is aiming and why it fails/succeeds
- In-world placement previews that highlight where the portals will land if you shoot them

feat: portal placement hud

---

src/Features/Camera.cpp
src/Features/PlayerTrace.cpp

Included:
- Make ghosts usable for coop
- add `sar_trace_export` to export the data to a csv file
- fix `sar_cam_path_remkf` completion

Make coop ghosts somewhat work, exporting player trace and small fix

---

src/Features/Hud/Hud.cpp

- `sar_hud_set_text_color` now can reset to default color by giving only idx arg
- `sar_hud_set_text` now accepts `#r` which resets to default color, and
- HUD text elements now inherit the color of the HUD properly

feat: use default hud color in texts

---

src/Features/PlayerTrace.cpp

feat: re-add oval portals

---

src/Features/PlayerTrace.cpp

fix: print trace name correctly

---

src/Cheats.cpp
src/Cheats.hpp
src/Modules/Client.cpp
src/Modules/Client.hpp

no sway
only took 1.5 years to make

feat: no sway

---

src/Features/ConfigPlus.cpp

feat: conds

---

src/Features/Speedrun/SpeedrunTimer.cpp
src/Features/Speedrun/SpeedrunTimer.hpp

also refactored legacy mtrigger customization into cvars

feat: sar_speedrun_skip_cutscenes

---

src/Features/Speedrun/SpeedrunTimer.cpp

i'm sorrryyyyyyyy i mad3e a a a bug in SAR but i ffixf it noww

fix: long fall bug

---

src/Cheats.cpp
src/Features/Hud/StrafeHud.cpp
src/Features/Hud/StrafeHud.hpp
src/Features/Hud/StrafeQuality.cpp
src/Features/Tas/TasPlayer.cpp
src/Features/Tas/TasPlayer.hpp
src/Modules/Client.cpp
src/Modules/Server.cpp
src/OffsetsData.hpp
src/SourceAutoRecord.vcxproj
src/SourceAutoRecord.vcxproj.filters

and fix strafe_quality display

feat: strafe hud

---

docs/cvars.md
docs/features.md
src/Features/Hud/Hud.cpp
src/Modules/Engine.cpp
src/Modules/Engine.hpp

Visual studio is really stupid and changed random thing at the bottom of src/SourceAutoRecord.vcxproj and i cant be bothered to fix it because it doesn't matter anyways

feat: sar_hud_fps

---

src/Features/Hud/Hud.cpp

The pre bounty (ending today) does not apply to this or the previous PR because that'd be mean, adding more work for mlugg day-of.

feat: `sar_hud_toggle_text`

---

src/Cheats.cpp
src/Cheats.hpp
src/Features/Tas/TasParser.cpp
src/Features/Tas/TasTools/StrafeTool.cpp
src/Modules/Server.cpp

also fix strafer avoiding speedlock with aircontrol

feat: `sar_autostrafe` cheat

---

src/Cheats.cpp
src/Features/ConfigPlus.cpp
src/Features/Hud/Hud.cpp
src/Features/Hud/Hud.hpp
src/Features/Hud/Toasts.cpp
src/Features/SegmentedTools.cpp
src/Features/Speedrun/SpeedrunTimer.cpp
src/Modules/Console.cpp
src/Utils.cpp
src/Utils.hpp

this thing should probably be in util at this point

fix: allow multiple arguments toast create

---

src/Features/FovChanger.cpp
src/Features/FovChanger.hpp

same as sar_force_fov except for cl_viewmodelfov
useful for some custom portal gun models

feat: force viewmodel fov

---

src/Features/Demo/GhostEntity.cpp
src/Utils/Math.hpp

ghost lerping had issues with angle lerping because angles weren't lerped properly. made angles lerp properly

fix: lerp ghost angles properly

---

docs/cvars.md
src/Event.hpp
src/Features/ConfigPlus.cpp
src/Features/Speedrun/SpeedrunTimer.cpp

Hope I did this correctly. Works on sp. I didn't test on coop though.

feat: `sar_on_speedrun_finish`

---

src/Features/ChallengeMode.cpp

fix trying to place flags while in a demo (ED_Alloc: No edicts yet)

Fix mel crash playing a demo after playing CM

---

src/SAR.cpp
src/SAR.hpp

Fix not being able to load the plugin after having it loaded once before.

fix: plugin loading

---

docs/cvars.md
src/Features/SteamTimeline.cpp

Made exclusively for Portal T-Rex.

feat: add cvar to disable adding splits to steam timeline

---

src/Modules/Server.cpp

yeah so just spawn the viewmodel again lol
legality of this is questionable (?)

fix: viewmodel disappearing

---

src/Modules/Surface.cpp
src/Modules/Surface.hpp
src/Utils/SDK/Math.hpp

Adding Vector2 and Bound
Overloading Surface to include them

Geometry utils

---

docs/cvars.md
src/Features/Hud/RhythmGame.cpp
src/Features/Hud/RhythmGame.hpp
src/Modules/Client.cpp
src/Modules/Server.cpp

Fun feature that shows rhythm game popups depending on groundframes
`sar_rhythmgame`
https://discord.com/channels/146404426746167296/730456805808799775/1272420549104107541
(previous pull was broke, sorry for duplicate)

feat: Rhythm Game Hud

---

docs/cvars.md
src/Features/Hud/RhythmGame.cpp
src/Features/Hud/RhythmGame.hpp

- Fixed popups showing up on both player's screens when playing coop
- Added sar_rhythmgame_combo and sar_rhythmgame_font as Hero and Dreadnox suggested
- Made the default font 64 (looks better imo)

Updates to sar_rhythmgame

---

src/Features/SteamTimeline.cpp

Added splits to sar_timeline_show_completed

feat: add splits to ``sar_timeline_show_completed``
